### ISSUE TITLE
Field Centric not functioning as intended.

### ISSUE THREAD

**Issue by kraj011** [FRCTeam2910/Common#92]
**Describe the bug**
Field centric works when the robot is in certain orientations. For example, when I reset the gyroscope value, it works as in it resets the new forward backward etc. movement. When I rotate the robot 180 degrees it also works as intended. However, when rotating while moving, it is as if the robot disable field centric mode and starts moving in robot centric mode. For example, when i start rotating and move backwards, it moves towards the robot's backward position and not the driver's backward position.

**To Reproduce**
1. Implement the example swerve code
2. Reset gyro using button
3. Rotate robot and move in any direction

**Expected behavior**
The robot should be moving forward always relative to the driver, not the robot. 

**Additional context**
I have tried implementing both the example swerve code found in this Repo and also the example swerve code in SDS's github profile, but both have the same issue.

**Comment by Kaboomboom3** [comment]
When you rotate the robot counter-clockwise does the gyro angle increase or decrease? Usually I see similar behavior when the gyro inversion is incorrect. The swerve kinematics expects the gyro angle to increase when the robot spins counter-clockwise.

**Comment by kraj011** [comment]
I'll double check when I have access to the robot tomorrow and I'll update this thread. So aside from inverting the gyro if necessary, is there anything else you recommend I do? Thanks!

**Comment by kraj011** [comment]
That did the trick! Thanks!
